services:
  - type: web
    name: OneBusAway API Server
    runtime: image
    image:
      url: wkulesza/oba-standalone:pks
    region: frankfurt
    plan: free
    numInstances: 1
    healthCheckPath: /api/where/current-time.json?key=org.onebusaway.iphone
    autoDeploy: true
    envVars:
      - fromGroup: OBA
      - key: REFRESH_INTERVAL
        value: 30
