services:
  - type: web
    name: OneBusAway API Server
    runtime: image
    image:
      url: wkulesza/oba-standalone:pks
    region: frankfurt
    plan: free
    numInstances: 1
    healthCheckPath: /api/where/current-time.json?key=org.onebusaway.iphone
    autoDeploy: true
    envVars:
      - key: TZ
        sync: true
      - key: GTFS_URL
        sync: true
      - key: VEHICLE_POSITIONS_URL
        sync: true
      - key: TRIP_UPDATES_URL
        sync: true
      - key: ALERTS_URL
        sync: false
      - key: FEED_API_KEY
        sync: false
      - key: FEED_API_VALUE
        sync: false
      - key: REFRESH_INTERVAL
        value: 30
      - key: AGENCY_ID
        sync: false
      - key: JDBC_USER
        sync: true
      - key: JDBC_PASSWORD
        sync: true
      - key: JDBC_URL
        value: jdbc:postgresql://goeuropa.net:5430/oba_database
