services:
  - type: web
    name: OneBusAway API Server
    runtime: image
    image:
      url: docker.io/opentransitsoftwarefoundation/onebusaway-api-webapp:2.5.13-otsf-v3.0.0
    region: oregon
    plan: free
    numInstances: 1
    healthCheckPath: /api/where/current-time.json?key=org.onebusaway.iphone
    autoDeploy: true
    envVars:
      - key: TZ
        sync: false
      - key: GTFS_URL
        sync: false
      - key: VEHICLE_POSITIONS_URL
        sync: false
      - key: TRIP_UPDATES_URL
        sync: false
      - key: ALERTS_URL
        sync: false
      - key: FEED_API_KEY
        sync: false
      - key: FEED_API_VALUE
        sync: false
      - key: REFRESH_INTERVAL
        value: 30
      - key: AGENCY_ID
        sync: false
      - key: JDBC_USER
        fromDatabase:
          name: oba-postgresql
          property: user
      - key: JDBC_PASSWORD
        fromDatabase:
          name: oba-postgresql
          property: password
      - key: JDBC_URL
        fromDatabase:
          name: oba-postgresql
          property: connectionString
      - key: JDBC_DRIVER
        value: org.postgresql.Driver
      - key: PORT
        value: 8080
    disk:
      name: Bundle
      mountPath: /bundle
      sizeGB: 1

databases:
  - name: oba-postgresql
    databaseName: obadb
    plan: basic-256mb
